### PR TITLE
fix: protect adds/gets/deletes during concurrent actions

### LINKED ISSUE #17: bug: concurrent map writes causes panic
Looks like this package uses `golang/groupcache/lru`, specifically:
https://github.com/golang/groupcache/blob/41bb18bfe9da5321badc438f91158cd790a33aa3/lru/lru.go#L22

Looks like it mentions that it is not concurrent safe, and this library doesn't add any locking or synchronization on top of it, which is problematic for any kind of http service. I'm running into an issue where reads are happening at the same time as writes, as shown below:

```console
fatal error: concurrent map writes

goroutine 386 [running]:
runtime.throw({0xd1f06d?, 0x404c4c?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0002d2d08 sp=0xc0002d2cd8 pc=0x4378d1
runtime.mapdelete(0x410770?, 0x9faf31?, 0xc3b360?)
        /usr/local/go/src/runtime/map.go:715 +0x3c9 fp=0xc0002d2d70 sp=0xc0002d2d08 pc=0x411309
github.com/golang/groupcache/lru.(*Cache).removeElement(0xc000032960, 0xc0001d96e0?)
        /home/user/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da/lru/lru.go:109 +0xdb fp=0xc0002d2db8 sp=0xc0002d2d70 pc=0x9fb29b
github.com/golang/groupcache/lru.(*Cache).Remove(...)
        /home/user/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da/lru/lru.go:91
ariga.io/entcache.(*LRU).Get(0xc000010620, {0xe63360?, 0xc000336090?}, {0xc064c0, 0xc000685380})
        /home/user/go/pkg/mod/ariga.io/entcache@v0.0.0-20211014200019-283c566a429b/level.go:117 +0x13b fp=0xc0002d2e28 sp=0xc0002d2db8 pc=0x9fd49b
ariga.io/entcache.(*Driver).Query(0xc0001d97a0, {0xe63360?, 0xc000336090}, {0xc00010ca00, 0xf5}, {0xbfa880?, 0xc00000ef18}, {0xca7d60?, 0xc0001ddac0?})
        /home/user/go/pkg/mod/ariga.io/entcache@v0.0.0-20211014200019-283c566a429b/driver.go:149 +0x23b fp=0xc0002d2ee8 sp=0xc0002d2e28 pc=0x9fba5b
entgo.io/ent/dialect/sql/sqlgraph.(*query).nodes(0xc0002d3008, {0xe63360, 0xc000336090}, {0xe63c20, 0xc0001d97a0})
        /home/user/go/pkg/mod/entgo.io/ent@v0.10.2-0.20220424193633-04e0dc936be9/dialect/sql/sqlgraph/graph.go:561 +0x11d fp=0xc0002d2fc0 sp=0xc0002d2ee8 pc=0x9c407d
entgo.io/ent/dialect/sql/sqlgraph.QueryNodes({0xe63360, 0xc000336090}, {0xe63c20?, 0xc0001d97a0?}, 0xc000116780)
        /home/user/go/pkg/mod/entgo.io/ent@v0.10.2-0.20220424193633-04e0dc936be9/dialect/sql/sqlgraph/graph.go:497 +0xa5 fp=0xc0002d3038 sp=0xc0002d2fc0 pc=0x9c3e05
mypkg/internal/ent.(*UserQuery).sqlAll(0xc000453540, {0xe63360, 0xc000336090}, {0x0, 0x0, 0xc05740?})
        /home/user/go/src/mypkg/internal/ent/user_query.go:343 +0x149 fp=0xc0002d3088 sp=0xc0002d3038 pc=0x9ec809
mypkg/internal/ent.(*UserQuery).All(0x9bebe5?, {0xe63360, 0xc000336090})
        /home/user/go/src/mypkg/internal/ent/user_query.go:172 +0x5f fp=0xc0002d30d0 sp=0xc0002d3088 pc=0x9eb47f
mypkg/internal/ent.(*UserQuery).Only(0xc000453540, {0xe63360, 0xc000336090})
        /home/user/go/src/mypkg/internal/ent/user_query.go:116 +0x6b fp=0xc0002d30f8 sp=0xc0002d30d0 pc=0x9eb10b
mypkg/internal/ent.(*UserClient).Get(0xc0001d9800, {0xe63360, 0xc000336090}, 0xc0006850f0?)
        /home/user/go/src/mypkg/internal/ent/client.go:202 +0x174 fp=0xc0002d3158 sp=0xc0002d30f8 pc=0x9d26f4
mypkg/internal/database.(*authService).Get(0xe5ebe0?, {0xe63360?, 0xc000336090?}, 0x4f33c5?)
        /home/user/go/src/mypkg/internal/database/auth_service.go:33 +0x2a fp=0xc0002d3188 sp=0xc0002d3158 pc=0xb18baa
mymiddleware.(*AuthHandler[...]).AddToContext.func1(0xc000214c00)
        /home/user/go/pkg/mod/mymiddleware@v0.0.0-20220504041011-2bea372285ae/auth.go:234 +0x15e fp=0xc0002d3260 sp=0xc0002d3188 pc=0xba3c1e
net/http.HandlerFunc.ServeHTTP(0x0?, {0xe610b0?, 0xc0002927d0?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3288 sp=0xc0002d3260 pc=0x6bcfef
mymiddleware.UseSecurityTxt.func1.1({0xe610b0?, 0xc0002927d0?}, 0xc000214c00?)
        /home/user/go/pkg/mod/mymiddleware@v0.0.0-20220504041011-2bea372285ae/security.go:73 +0x127 fp=0xc0002d32d0 sp=0xc0002d3288 pc=0x7967a7
net/http.HandlerFunc.ServeHTTP(0xc000684f50?, {0xe610b0?, 0xc0002927d0?}, 0x15?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d32f8 sp=0xc0002d32d0 pc=0x6bcfef
mymiddleware.UseRobotsTxt.func1.1({0xe610b0, 0xc0002927d0}, 0xc000214c00?)
        /home/user/go/pkg/mod/mymiddleware@v0.0.0-20220504041011-2bea372285ae/security.go:40 +0x22f fp=0xc0002d3368 sp=0xc0002d32f8 pc=0x7964cf
net/http.HandlerFunc.ServeHTTP(0xc000285a70?, {0xe610b0?, 0xc0002927d0?}, 0x15?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3390 sp=0xc0002d3368 pc=0x6bcfef
github.com/go-chi/httprate.(*rateLimiter).Handler.func1({0xe610b0, 0xc0002927d0}, 0xc000286300?)
        /home/user/go/pkg/mod/github.com/go-chi/httprate@v0.5.3/limiter.go:129 +0x9ad fp=0xc0002d3510 sp=0xc0002d3390 pc=0x75988d
net/http.HandlerFunc.ServeHTTP(0xc00028a540?, {0xe610b0?, 0xc0002927d0?}, 0xc00069ae80?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3538 sp=0xc0002d3510 pc=0x6bcfef
github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1({0x7f331ce3ee38?, 0xc00069ae80}, 0xc000214c00)
        /home/user/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/compress.go:213 +0x25e fp=0xc0002d35e8 sp=0xc0002d3538 pc=0x7508de
net/http.HandlerFunc.ServeHTTP(0x40ff45?, {0x7f331ce3ee38?, 0xc00069ae80?}, 0xc000095668?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3610 sp=0xc0002d35e8 pc=0x6bcfef
github.com/go-chi/chi/v5/middleware.StripSlashes.func1({0x7f331ce3ee38, 0xc00069ae80}, 0xc000214c00)
        /home/user/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/strip.go:30 +0x139 fp=0xc0002d3650 sp=0xc0002d3610 pc=0x755a59
net/http.HandlerFunc.ServeHTTP(0x203000?, {0x7f331ce3ee38?, 0xc00069ae80?}, 0x4?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3678 sp=0xc0002d3650 pc=0x6bcfef
mymiddleware.UseNextURL.func1({0x7f331ce3ee38, 0xc00069ae80}, 0xc000214c00)
        /home/user/go/pkg/mod/mymiddleware@v0.0.0-20220504041011-2bea372285ae/redirect.go:37 +0x1dc fp=0xc0002d3780 sp=0xc0002d3678 pc=0x7957dc
net/http.HandlerFunc.ServeHTTP(0xe63360?, {0x7f331ce3ee38?, 0xc00069ae80?}, 0x1351520?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d37a8 sp=0xc0002d3780 pc=0x6bcfef
mymiddleware.UseStructuredLogger.func1.1({0xe62970, 0xc0001da1c0}, 0xc000214a00)
        /home/user/go/pkg/mod/mymiddleware@v0.0.0-20220504041011-2bea372285ae/logger.go:84 +0x485 fp=0xc0002d38a0 sp=0xc0002d37a8 pc=0x793fc5
net/http.HandlerFunc.ServeHTTP(0x0?, {0xe62970?, 0xc0001da1c0?}, 0x88?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d38c8 sp=0xc0002d38a0 pc=0x6bcfef
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0xe62970?, 0xc0001da1c0?}, 0xe58401?)
        /home/user/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/recoverer.go:38 +0x83 fp=0xc0002d3928 sp=0xc0002d38c8 pc=0x753ae3
net/http.HandlerFunc.ServeHTTP(0xe63360?, {0xe62970?, 0xc0001da1c0?}, 0xe58408?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3950 sp=0xc0002d3928 pc=0x6bcfef
github.com/go-chi/chi/v5/middleware.RequestID.func1({0xe62970, 0xc0001da1c0}, 0xc000214900)
        /home/user/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/request_id.go:76 +0x354 fp=0xc0002d3a00 sp=0xc0002d3950 pc=0x755774
net/http.HandlerFunc.ServeHTTP(0xe632b8?, {0xe62970?, 0xc0001da1c0?}, 0x130c500?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002d3a28 sp=0xc0002d3a00 pc=0x6bcfef
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc00028e660, {0xe62970, 0xc0001da1c0}, 0xc000214800)
        /home/user/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x442 fp=0xc0002d3a98 sp=0xc0002d3a28 pc=0x7041a2
net/http.serverHandler.ServeHTTP({0xc0000c77a0?}, {0xe62970, 0xc0001da1c0}, 0xc000214800)
        /usr/local/go/src/net/http/server.go:2916 +0x43b fp=0xc0002d3b58 sp=0xc0002d3a98 pc=0x6c0a9b
net/http.(*conn).serve(0xc0002b20a0, {0xe63360, 0xc0005585d0})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7 fp=0xc0002d3fb8 sp=0xc0002d3b58 pc=0x6bba97
net/http.(*Server).Serve.func3()
        /usr/local/go/src/net/http/server.go:3071 +0x2e fp=0xc0002d3fe0 sp=0xc0002d3fb8 pc=0x6c13ee
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0002d3fe8 sp=0xc0002d3fe0 pc=0x46a321
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
```

### PR DESCRIPTION
**Pull request by lrstanley**
Resolves #17. Looks as though #18 was only protecting reads, whereas this should protect all actions, and utilizes a read-write mutex, to improve performance.

### CODE REVIEW

File: level.go [hunk 1]
```diff
@@ -108,20 +109,25 @@ func (l *LRU) Add(_ context.Context, k Key, e *Entry, ttl time.Duration) error {
...
 	case *Entry:
 		return e, nil
 	case *entry:
 		if time.Now().Before(e.expiry) {
 			return e.Entry, nil
 		}
+
+		l.mu.Lock()
 		l.Cache.Remove(k)
+		l.mu.Unlock()
```
Comment (masseelch) [inline level.go:130]: Correct me if I am wrong, but the `Lock` here will wait for all read locks to be released before attempting to write, correct? If so, this is a deadlock, no?

This is the reason I used the `sync.Mutex` instead of a `sync.RWMutex` in the first place.

https://pkg.go.dev/sync#RWMutex.Lock

Comment (masseelch) [inline level.go:130]: Correct me if I am wrong, but the Lock here will wait for all read locks to be released before attempting to write, correct? If so, this is a deadlock, since this method acquires a `RLock`, that is only released on `defer`, no?

This is the reason I used the sync.Mutex instead of a sync.RWMutex in the first place.

https://pkg.go.dev/sync#RWMutex.Lock

File: level.go [hunk 2]
```diff
@@ -130,7 +136,10 @@ func (l *LRU) Get(_ context.Context, k Key) (*Entry, error) {
 
 // Del deletes an entry from the cache.
 func (l *LRU) Del(_ context.Context, k Key) error {
+	l.mu.Lock()
 	l.Cache.Remove(k)
+	l.mu.Unlock()
+
```
Comment (a8m) [inline level.go:142]:
```suggestion
```
Remove extra newlines.

File: level.go [hunk 3]
```diff
@@ -108,20 +109,25 @@ func (l *LRU) Add(_ context.Context, k Key, e *Entry, ttl time.Duration) error {
...
 	}
+
 	switch e := e.(type) {
 	case *Entry:
 		return e, nil
 	case *entry:
 		if time.Now().Before(e.expiry) {
 			return e.Entry, nil
 		}
+
```
Comment (a8m) [inline level.go:127]:
```suggestion
```

File: level.go [hunk 4]
```diff
@@ -108,20 +109,25 @@ func (l *LRU) Add(_ context.Context, k Key, e *Entry, ttl time.Duration) error {
 
 // Get gets an entry from the cache.
 func (l *LRU) Get(_ context.Context, k Key) (*Entry, error) {
-	l.lock.Lock()
-	defer l.lock.Unlock()
+	l.mu.RLock()
 	e, ok := l.Cache.Get(k)
+	l.mu.RUnlock()
+
```
Comment (a8m) [inline level.go:115]:
```suggestion
```

File: level.go [hunk 5]
```diff
@@ -90,14 +90,15 @@ type (
...
 	}
 }
 
 // Add adds the entry to the cache.
 func (l *LRU) Add(_ context.Context, k Key, e *Entry, ttl time.Duration) error {
-	l.lock.Lock()
-	defer l.lock.Unlock()
+	l.mu.Lock()
+	defer l.mu.Unlock()
+
```
Comment (a8m) [inline level.go:101]:
```suggestion
```

File: level.go [hunk 6]
```diff
@@ -75,8 +75,8 @@ var ErrNotFound = errors.New("entcache: entry was not found")
 type (
 	// LRU provides an LRU cache that implements the AddGetter interface.
 	LRU struct {
+		mu *sync.RWMutex
```
Comment (a8m) [inline level.go:78]:
```suggestion
		mu sync.RWMutex
```

The pointer here is not really needed, as all methods get pointer receiver.

File: level.go [hunk 7]
```diff
@@ -90,14 +90,15 @@ type (
 func NewLRU(maxEntries int) *LRU {
 	return &LRU{
 		Cache: lru.New(maxEntries),
-		lock:  &sync.Mutex{},
+		mu:    &sync.RWMutex{},
```
Comment (a8m) [inline level.go:93]:
```suggestion
```

Use the zero value (after removing the pointer above).

**Review by a8m — COMMENTED** [review]
Thanks for the contribution, @lrstanley 🙏 

I added a few minor style comments.

File: level.go (hunk 1 above)
Comment (masseelch) [reply level.go:130]: I now see there is no defer. Oops 😬. It ire my comment.

**Comment by lrstanley** [comment]
To me, the newlines help split the logic and prevent the code from feeling cramped, to each their own. 🙂
